version: "3" # composeファイルのバージョン
services:
  spring: # サービス名
    container_name: spring
    build:
      context: .
      dockerfile: docker/spring/Dockerfile
    tty: true # ②コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "8080:8080"
    volumes:
      - ./src :/src # ③マウントディレクトリ
